<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>navigrid_bringup</name>
  <version>1.0.0</version>
  <description>Master orchestration launch package for NaviGrid: The Adaptive Path Challenge</description>
  <maintainer email="aryan@example.com">Aryan</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>navigrid_description</exec_depend>
  <exec_depend>navigrid_gazebo</exec_depend>
  <exec_depend>navigrid_navigation</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
